[[breaking-changes-1.4]]
== 1.4 版本中的重大变更

本节讨论了应用程序升级 Elasticsearch 1.x 到 1.4 版本时你应该要注意到的一些变更.

[float]
=== 过滤器

在使用 `1.4.0` 或以上版本创建的索引中, 过滤查询只会查询索引中的映射中已经存在的字段. 有两种方
式可以确保一个字段映射存在:

* 通过 <<indices-create-index,create index>> 或 <<indices-put-mapping,put mapping>>
api新增或更新一个映射.
* 在注册查询之前过滤文档. 过滤一个文档可以动态地增加字段映射, 当索引一个文档时也会以同样的方式
发生.

[float]
=== 别名

<<indices-aliases,别名>> 可以包括 <<query-dsl,过滤器>> , 它会自动应用于通过别名执行的任
何搜索. `1.4.0` 或以上版本创建的 <<filtered, 过滤后的别名>> 仅可以指向由别名指向的单个索引
 (或多个索引) 的映射中已存在的字段名.

通过 <<indices-create-index,create index>> 或者 <<indices-put-mapping,put mapping>>
api来新增或更新一个映射.

[float]
=== 索引 API

即使没有 warmers, <<warmer-retrieving, get warmer api>> 也将会为 `warmers` 返回一个
section. 这样就确保了下面两个示例是等价的:

[source,js]
--------------------------------------------------
curl -XGET 'http://localhost:9200/_all/_warmers'

curl -XGET 'http://localhost:9200/_warmers'
--------------------------------------------------

即使没有别名, <<alias-retrieving, get alias api>> 也将会为 `aliases` 返回一个section.
 这样就确保了下面两个示例是等价的:

[source,js]
--------------------------------------------------
curl -XGET 'http://localhost:9200/_all/_aliases'

curl -XGET 'http://localhost:9200/_aliases'
--------------------------------------------------

即使没有映射 <<indices-get-mapping, get mapping api>> 也将会为 `mappings` 返回一个
section. 这样就确保了下面两个示例是等价的:

[source,js]
--------------------------------------------------
curl -XGET 'http://localhost:9200/_all/_mappings'

curl -XGET 'http://localhost:9200/_mappings'
--------------------------------------------------

[float]
=== Bulk UDP

Bulk UDP 已经被废弃并且将会在 2.0 版本中移除. 你应该使用 <<docs-bulk,标准的 bulk API>>
作为替代.为了充分运作, 每个集群必须要有一个当选的 master 节点. 一旦节点失去当选的 master 节
点, 它将拒绝默写或全部的操作.

[float]
=== Zen discovery

在 `1.4.0.Beta1` 版本之前, 当某个节点失去当选的 master 节点时, 所有的操作都会被拒绝.
从 `1.4.0.Beta1` 版本后默认只有写操作会被拒绝. 读操作仍将提供所获得的节点信息, 这样可能会导
致信息只是部分的并且可能也已经过期.如果不希望使用默认操作, 那么可以启用 `1.4.0.Beta1` 版本之
前的行为, 参见: <<modules-discovery-zen,no-master-block>>

[float]
=== More Like This字段

为了限制 <<query-dsl-mlt-query, More Like This查询>> 设置为一个明确的 `field`,
More Like This字段查询已经被废弃. 它将会在2.0版本中被移除.

[float]
=== MVEL 已经被废弃

Groovy 是 Elasticsearch 中最新默认的脚本语言, 并且在 `sandbox` 模式中默认启用.  MVEL 已
经从核心中删除掉了, 但是仍然可以作为插件使用:https://github.com/elasticsearch/elasticsearch-lang-mvel
