[[breaking_20_aggregation_changes]]
=== 聚合变更

==== 文档最小数量默认设置为0

`histogram` 和 `date_histogram` 聚合现在的 `min_doc_count` 的默认值是 `0` 而不是 `1`.

==== 用于日期字段的时区(Timezone)

指定用于查询或聚合中类型为 `date` 的字段上的 `time_zone` 参数现在要么是一个 ISO 8601 UTC
偏移量, 要么是一个时区ID. 例如, `+1:00` 这个值现在必须写成 `+01:00`.

==== 时区和偏移量

`histogram` 和 `date_histogram` 聚合现在支持一个简化的 `offset` 选项来替代之前的 `pre_offset`
和 `post_offset` 舍入选项. 不用为底层的 bucket 指定两个单独的平行迁移, `offset` 选项根据
它的参数将 bucket 边界往正的或者反的方向移动.

`date_histogram` 选项 `pre_zone` 和 `post_zone` 现在被 `time_zone` 选项取代. `time_zone`
的行为等同于之前的 `pre_zone` 选项. 现在将 `time_zone` 设置成像 "+01:00" 这样的值会导致
bucket计算被应用到指定的时区.`key` 返回的是 UTC 时间戳, 但是 `key_as_string` 返回的是指定
的时区.

除此之外, 由于我们总是返回 UTC 日期和 bucket keys, `pre_zone_adjust_large_interval`
已经被移除.

==== 包括/排除 terms

`terms` 聚合上的 `include`/`exclude` 过滤器现在使用同样的 <<regexp-syntax,正则表达式查询>>
语法而不是 Java 正则表达式语法. 虽然简单的正则表达式仍然可以工作, 但是更复杂可能需要重写. 此
外, 不再支持 `flags` 参数.

==== 布尔字段

`boolean` 字段上的聚合现在返回 `0` 和 `1` 作为键, 以及 `"true"` 和 `"false"` 作为字符
串键.  想要了解更多信息参见 <<migration-bool-fields>>.


==== Java聚合类

`date_histogram` 聚合现在在响应中返回一个 `Histogram` 对象, 并且 `DateHistogram` 类已
经被移除.  类似地, `date_range`, `ipv4_range` 以及 `geo_distance` 聚合全都在响应中返回
一个 `Range` 对象, 并且 `IPV4Range`, `DateRange` 以及 `GeoDistance` 类已经被移除.

这样做的动机是为了对于 Range 和 Histogram 聚合能有一个简单的响应 API 而不用管被查询数据的类
型.为了支持它, 在应用于所有 bucket 聚合的 `MultiBucketAggregation` 接口中做了一些改变:

* `getKey()` 方法现在返回 `Object` 而不是 `String`. 实际返回的对象类型取决于请求的聚合类
型(例如, 对于这个方法 `date_histogram` 将会返回一个 `DateTime` 对象, 而 `histogram` 将
返回一个 `Number` 对象).
* 新增了一个用于返回键的字符串描述的 `getKeyAsString()` 方法.
* 所有其它 `getKeyAsX()` 方法已经被移除.
* `getBucketAsKey(String)` 方法已经在除了 `filters` 和 `terms` 聚合之外的所有聚合上移除.
