[[breaking_20_setting_changes]]
=== 设置变更

==== 命令行标志

使用单个破折号的命令行标志现在必须指定为第一个参数.例如如果之前使用的是:

[source,sh]
---------------
./elasticsearch --node.name=test_node -Des.path.conf=/opt/elasticsearch/conf/test_node
---------------

那么现在需要改变成:

[source,sh]
---------------
./elasticsearch -Des.path.conf=/opt/elasticsearch/conf/test_node --node.name=test_node
---------------

这样这个标志才会生效.

[[migration-script-settings]]
==== 脚本设置

`script.disable_dynamic` 节点设置已经被 <<enable-dynamic-scripting,脚本文档>> 中描述
的细粒度的脚本设置所替代.下面的设置之前用于启用动态的或内联的脚本:

[source,yaml]
---------------
script.disable_dynamic: false
---------------

想要实现相同的结果需要在 `elasticsearch.yml` 文件中使用下面两个设置来替换它:

[source,yaml]
---------------
script.inline: on
script.indexed: on
---------------

==== 时间和字节大小设置需要的单位

任何接受时间或字节值的设置现在必须要指定单位. 例如, 很容易设置 `refresh_interval` 为 1
*毫秒* 而不是 1 秒:

[source,js]
---------------
PUT _settings
{
  "index.refresh_interval": 1
}
---------------

在 2.0 版本中, 上述请求会抛出一个异常. 刷新时间间隔应该设置成 `"1s"` 来表示1秒.

==== 合并以及合并节流设置

分层合并策略是现在唯一支持的合并策略. 下面这些设置已经被移除:

* `index.merge.policy.type`
* `index.merge.policy.min_merge_size`
* `index.merge.policy.max_merge_size`
* `index.merge.policy.merge_factor`
* `index.merge.policy.max_merge_docs`
* `index.merge.policy.calibrate_size_by_deletes`
* `index.merge.policy.min_merge_docs`
* `index.merge.policy.max_merge_docs`

合并节流现在使用一个反馈循环来自动节流. 下面这些设置已经被移除:

* `indices.store.throttle.type`
* `indices.store.throttle.max_bytes_per_sec`
* `index.store.throttle.type`
* `index.store.throttle.max_bytes_per_sec`

==== 影子副本设置

`node.enable_custom_paths` 设置已经被移除并且使用 `path.shared_data` 设置作为替代来允许
使用自定义路径的影子副本与安全管理器一起工作. 例如, 如果你之前的配置是:

[source,yaml]
------
node.enable_custom_paths: true
------

并且你使用 `index.data_path` 设置为 `/opt/data/my_index` 的影子副本创建一个索引, 如下:

[source,js]
--------------------------------------------------
PUT /my_index
{
  "index": {
    "number_of_shards": 1,
    "number_of_replicas": 4,
    "data_path": "/opt/data/my_index",
    "shadow_replicas": true
  }
}
--------------------------------------------------

对于 2.0 版本, 你将需要设置 `path.shared_data` 为索引的 data_path 的一个父目录, 即像下面这样:

[source,yaml]
-----------
path.shared_data: /opt/data
-----------

==== 重命名资源监视器设置

用于配置资源监视器的设置名称已经被重命名以防止与监视器插件冲突

* `watcher.enabled` 现在是 `resource.reload.enabled`
* `watcher.interval` 现在是 `resource.reload.interval`
* `watcher.interval.low` 现在是 `resource.reload.interval.low`
* `watcher.interval.medium` 现在是 `resource.reload.interval.medium`
* `watcher.interval.high` 现在是 `resource.reload.interval.high`

==== Hunspell字典配置

`indices.analysis.hunspell.dictionary.location` 参数已经被移除, 并且永久使用 `<path.conf>/hunspell`.

==== CORS allowed origins

CORS 允许的起源设置 `http.cors.allow-origin` 不再有默认值.之前的默认值是 `*`, 它允许任何
源发起的 CORS 请求并且被认为是不安全的. `http.cors.allow-origin` 设置应该仅指定允许的源, 像这样:

[source,yaml]
---------------
http.cors.allow-origin: /https?:\/\/localhost(:[0-9]+)?/
---------------

==== JSONP支持

JSONP的回调支持现在已经被移除. CORS应该优于 AJAX 用于访问 Elasticsearch:

[source,yaml]
---------------
http.cors.enabled: true
http.cors.allow-origin: /https?:\/\/localhost(:[0-9]+)?/
---------------

==== 内存索引

Elasticsearch 中已经移除了 `memory` / `ram` 存储 (`index.store.type`) 选项. 将不再
支持内存索引.

==== 截取日志消息

日志消息现在被截取到 10,000 个字符. 可以使用 `logging.yml` 配置文件中的 `file.layout.conversionPattern`
设置来改变.

==== 自定义配置文件

现在已不太可能使用 `CONF_FILE` 环境变量, 或 `-Des.config`, `-Des.default.config`, 或者
`-Delasticsearch.config` 参数来指定一个自定义配置文件.

相反, 配置文件必须命名为 `elasticsearch.yml` 并且必须放置在默认的 `config/` 目录下, 除非
指定一个自定义配置路径.

自定义配置文件目录的路径可以使用如下方式指定:

[source,sh]
--------------
./bin/elasticsearch --path.conf=/path/to/conf/dir
./bin/plugin -Des.path.conf=/path/to/conf/dir install analysis-icu
--------------

当使用 RPM 或 debian 包时, 插件脚本和init/service 脚本将查询 `CONF_DIR` 环境变量来检查自定义
配置路径. `CONF_DIR` 变量的值可以在位于 `/etc/default/elasticsearch` 或 `/etc/sysconfig/elasticsearch`
中的环境配置文件中设置.

==== 移除 `ES_CLASSPATH`

`ES_CLASSPATH` 环境变量不再用来设置类路径. 外部库应该优先使用插件机制来加载, 或者如果你真的
需要的话, 可以拷贝到 `lib/` 目录.
