[[index-modules-slowlog]]
== 慢日志

[float]
[[search-slow-log]]
=== 搜索慢日志

分片级别的慢搜索日志可以将慢搜索（查询和获取阶段）通过日志的方式记录在专门的文件中。

查询或者获取阶段的阈值都分别可以定义，下面是一个例子：

[source,yaml]
--------------------------------------------------
index.search.slowlog.threshold.query.warn: 10s
index.search.slowlog.threshold.query.info: 5s
index.search.slowlog.threshold.query.debug: 2s
index.search.slowlog.threshold.query.trace: 500ms

index.search.slowlog.threshold.fetch.warn: 1s
index.search.slowlog.threshold.fetch.info: 800ms
index.search.slowlog.threshold.fetch.debug: 500ms
index.search.slowlog.threshold.fetch.trace: 200ms
--------------------------------------------------

所有上面的设置都是 _dynamic_ 并且可以针对每个索引设置。

默认情况下， 慢日志没有开启（设成 `-1`）。 级别（ `warn`, `info`,
`debug`, `trace`）用来控制日志的输出级别，并不是所有的级别都是必须的（如，可以只设置 `warn`
级别的日志）， 使用多个级别的好处是可以快速的通过 “grep” 查询对应级别的日志。

日志是基于分片这个级别的， 也就是说记录的是一个搜索请求在指定分片上得执行情况。一个搜索请求会被
广播到多个分片上去执行，而慢日志并不包含这个请求的整个生命周期。这样做的好处是，可以将日志和所执行
该请求的机器对应起来。

日志文件默认使用下面的配置（在 `logging.yml`中）：

[source,yaml]
--------------------------------------------------
index_search_slow_log_file:
  type: dailyRollingFile
  file: ${path.logs}/${cluster.name}_index_search_slowlog.log
  datePattern: "'.'yyyy-MM-dd"
  layout:
    type: pattern
    conversionPattern: "[%d{ISO8601}][%-5p][%-25c] %m%n"
--------------------------------------------------

[float]
[[index-slow-log]]
=== 索引慢日志

索引慢日志功能上和搜索慢日志类似。 索引慢日志文件以 `_index_indexing_slowlog.log`结尾，
日志和阈值的配置和搜索慢日志一样在 elasticsearch.yml中配置。索引慢日志例子：

[source,yaml]
--------------------------------------------------
index.indexing.slowlog.threshold.index.warn: 10s
index.indexing.slowlog.threshold.index.info: 5s
index.indexing.slowlog.threshold.index.debug: 2s
index.indexing.slowlog.threshold.index.trace: 500ms
index.indexing.slowlog.level: info
index.indexing.slowlog.source: 1000
--------------------------------------------------

所有上面的设置都是 _dynamic_ 并且可以针对每个索引设置。

Elasticsearch默认会记录 _source 中的1000个字符在慢日志文件中，你可以通过
 `index.indexing.slowlog.source` 改变此值， 设成 `false` 或 `0` 将不会记录source的内容，
 如果设成 `true` 则会完整记录整个source字段的值，而不管大小事多少。

索引慢日志文件默认使用下面的配置（在 `logging.yml`中）：

[source,yaml]
--------------------------------------------------
index_indexing_slow_log_file:
    type: dailyRollingFile
    file: ${path.logs}/${cluster.name}_index_indexing_slowlog.log
    datePattern: "'.'yyyy-MM-dd"
    layout:
      type: pattern
      conversionPattern: "[%d{ISO8601}][%-5p][%-25c] %m%n"
--------------------------------------------------
