[[cluster-nodes-info]]
== 节点信息

集群节点信息 API 允许检索一个或多个 (或全部) 的集群节点信息.

[source,js]
--------------------------------------------------
curl -XGET 'http://localhost:9200/_nodes'
curl -XGET 'http://localhost:9200/_nodes/nodeId1,nodeId2'
--------------------------------------------------

第一个命令检索集群中所有节点的信息.第二个命令有选择性的只检索 `nodeId1` 和 `nodeId2`这两个节点的信息. 所有节点的选择性选项都在 <<cluster-nodes,这里>> 有解释.

它默认只返回节点所有属性和核心设置. 它也允许只获取 `settings`, `os`, `process`, `jvm`,
`thread_pool`, `transport`, `http` 以及 `plugins` 信息:

[source,js]
--------------------------------------------------
curl -XGET 'http://localhost:9200/_nodes/process'
curl -XGET 'http://localhost:9200/_nodes/_all/process'
curl -XGET 'http://localhost:9200/_nodes/nodeId1,nodeId2/jvm,process'
# 同上
curl -XGET 'http://localhost:9200/_nodes/nodeId1,nodeId2/info/jvm,process'

curl -XGET 'http://localhost:9200/_nodes/nodeId1,nodeId2/_all
--------------------------------------------------

`_all` 标识可以设置用于返回所有的信息 - 或者你可以简单的忽略它.

[float]
[[os-info]]
==== 操作系统信息

`os` 标识可以设置用来检索有关操作系统的信息:

`os.refresh_interval_in_millis`::
	OS数据统计的刷新时间间隔

`os.name`::
	操作系统名称 (例如: Linux, Windows, Mac OS X)

`os.arch`::
	JVM 架构名称 (例如: amd64, x86)

`os.version`::
	操作系统版本

`os.available_processors`::
	Java虚拟机 (Java virtual machine) 可用的处理器数量

[float]
[[process-info]]
==== 进程信息

`process` 标识可以设置用来检索有关当前运行进程的信息:

`process.refresh_interval_in_millis`::
	进程统计数据的刷新时间间隔

`process.id`::
	进程标识符 (PID)

`process.mlockall`::
	表明进程的地址空间在内存中是否成功地被锁定

[float]
[[plugins-info]]
==== 插件信息

`plugins` - 如果设置了, 结果会包含每个节点加载的插件的详细信息:

* `name`: 插件名称
* `description`: 插件描述, 如果有的话
* `site`: 如果插件是一个网站插件则为 `true`
* `jvm`: 如果插件是一个运行在 JVM 中的插件则为 `true`
* `url`: 如果插件是一个网站插件则为 URL

返回结果看起来像下面这样:

[source,js]
--------------------------------------------------
{
  "cluster_name" : "test-cluster-MacBook-Air-de-David.local",
  "nodes" : {
    "hJLXmY_NTrCytiIMbX4_1g" : {
      "name" : "node4",
      "transport_address" : "inet[/172.18.58.139:9303]",
      "hostname" : "MacBook-Air-de-David.local",
      "version" : "0.90.0.Beta2-SNAPSHOT",
      "http_address" : "inet[/172.18.58.139:9203]",
      "plugins" : [ {
        "name" : "test-plugin",
        "description" : "test-plugin description",
        "site" : true,
        "jvm" : false
      }, {
        "name" : "test-no-version-plugin",
        "description" : "test-no-version-plugin description",
        "site" : true,
        "jvm" : false
      }, {
        "name" : "dummy",
        "description" : "No description found for dummy.",
        "url" : "/_plugin/dummy/",
        "site" : false,
        "jvm" : true
      } ]
    }
  }
}
--------------------------------------------------
