[[allocation-filtering]]
=== 分片分配过滤

在 <<index-modules-allocation>> 中提供了基于 *索引* 的配置选项来控制分片在节点间的分配，
集群级别的分片分配过滤让你可以开启或者禁止任何索引上的分片分配到给定的节点上去。

集群级别的分片分配过滤的典型使用场景是当你需要退役一个节点时，你需要在关闭这个节点之前，将其上的
分片从这个节点移到其他节点上去。

比如，我们可以通过如下设置IP地址的方式退役一个节点：
[source,js]
--------------------------------------------------
PUT /_cluster/settings
{
  "transient" : {
    "cluster.routing.allocation.exclude._ip" : "10.0.0.1"
  }
}
--------------------------------------------------
// AUTOSENSE

NOTE: 仅当分配规则是可行的，即不破坏其他分配规则时，分片才会被分配，比如：从不分配主分片和分片
副本给同一个节点。

集群级别的分片分配过滤的工作方式与索引级别的分片分配过滤是一样的（细节见
 <<index-modules-allocation>> ）。
可用的 _dynamic_ 设置如下，其中  `{attribute}` 指的是任意一个节点属性：

`cluster.routing.allocation.include.{attribute}`::

    将索引分配给一个节点，该节点的 `{attribute}` 至少包含以半角逗号分隔值中的一项。


`cluster.routing.allocation.require.{attribute}`::

    将索引分配给一个节点，该节点的 `{attribute}` 必须包含以半角逗号分隔值中的全部项。

`cluster.routing.allocation.exclude.{attribute}`::

    将索引分配给一个节点，该节点的 `{attribute}` 必须不包含以半角逗号分隔值中的项。

特别属性也是支持的：

[horizontal]
`_name`::   通过节点名称匹配节点
`_ip`::     通过IP地址匹配 (与主机关联的IP地址）
`_host`::   通过主机名匹配节点。

所有属性值支持通配符。如
[source,js]
------------------------
PUT _cluster/settings
{
  "transient": {
    "cluster.routing.allocation.include._ip": "192.168.2.*"
  }
}
------------------------
// AUTOSENSE
