[[disk-allocator]]
=== 基于磁盘的分片分配

Elasticsearch通过调节一个节点上可用磁盘空间来决定是分配新的分片给这个节点还是将分片从节点上
移除。

下面是可以在 `elasticsearch.yml`中设置的配置项，或者可以通过
<<cluster-update-settings,cluster-update-settings>> API动态改变这些值。

`cluster.routing.allocation.disk.threshold_enabled`::

    默认为 `true`。 设置成 `false` 则可以禁止磁盘分片分配器。

`cluster.routing.allocation.disk.watermark.low`::

    控制磁盘使用率的低水位，默认为85%，这意味着当磁盘使用率达到85%后，ES将不会分配新的分片给
    该节点了。 该值也可以是一个绝对大小的字节数值（如 500mb），当磁盘空间小于配置的这个值后，
    ES也不会分配新分片了。

`cluster.routing.allocation.disk.watermark.high`::

    控制磁盘使用率的高水位，默认为90%，意味着当磁盘使用率达到90%后，ES将尝试将分片转移到其它
    节点上。该值也可以象设置低水位一样，设置一个绝对值，当磁盘空间小于该值后，就会转移分片。

NOTE: 百分比指的是使用率，字节值指的是剩余空间。这可能导致混淆，因为将颠倒高低值。例如，可以设置
低水位为10gb，高水位为5gb，而不是反过来设置。


`cluster.info.update.interval`::

    Elasticsearch多久需要检查集群中每个节点的磁盘使用率，默认为 `30s`。

`cluster.routing.allocation.disk.include_relocations`::

    默认是 +true+, 这表示Elasticsearch会再计算节点磁盘使用率时将正在迁移的分片所占用的空间
    也计算进去。这样可能导致磁盘使用率计算不准，例如在计算到磁盘使用率达到90%时，可能包含了正在
    迁移的分片的大小。


下面是一个例子，设置低水位不超过80%，高水位需要预留50Gb空间，并且每分钟检查并更新一下集群的信息。

[source,js]
--------------------------------------------------
PUT /_cluster/settings
{
  "transient": {
    "cluster.routing.allocation.disk.watermark.low": "80%",
    "cluster.routing.allocation.disk.watermark.high": "50gb",
    "cluster.info.update.interval": "1m"
  }
}
--------------------------------------------------
// AUTOSENSE

NOTE: 在2.0.0之前，当使用多个数据路径时， 磁盘阈值计算只会考虑总的数据使用率(如果你有两个数据
  路径，一个总容量是100b，使用了50b（50%使用率），另一个数据盘总容量50b，使用了40b(80%使用率)
  计算得到的结果是总量150b，使用了90b)。在2.0.0中， 每个磁盘的最小最大值时分别统计的。
