[[shard-allocation-filtering]]
=== Shard Allocation Filtering

索引分片的分配过滤器让你可以指定哪个节点可以用来服务特定索引中得分片。

NOTE: 下面所解释的索引级别的分片分配过滤器可以和集群级别的分配过滤器
<<shards-allocation>> 一起协同工作。

可以在节点启动时设置一些元数据属性。比如，节点可以象如下一样分片一个 `rack` 和 `group`属性：

[source,sh]
------------------------
bin/elasticsearch --node.rack rack1 --node.size big  <1>
------------------------
<1> 这些属性值也可以在 `elasticsearch.yml`中指定。

这些元数据属性可以使用配置项
`index.routing.allocation.*` 来分配一个索引给特定组的节点。比如，我们可以通过以下配置将索引 `test` 移
到 `big` 或 `medium` 节点中。

[source,js]
------------------------
PUT test/_settings
{
  "index.routing.allocation.include.size": "big,medium"
}
------------------------
// AUTOSENSE

同样的，我们也可以通过 `exclude` 将索引 `test` 从 `small` 这个组中移除掉：

[source,js]
------------------------
PUT test/_settings
{
  "index.routing.allocation.exclude.size": "small"
}
------------------------
// AUTOSENSE

可以设置多个规则，这意味着所有规则条件必须同时满足。 例如， 我们可以将索引 `test` 移到
`big` 组，并且是 `rack1` 这个rack。

[source,js]
------------------------
PUT test/_settings
{
  "index.routing.allocation.include.size": "big",
  "index.routing.allocation.include.rack": "rack1"
}
------------------------
// AUTOSENSE

NOTE: 如果某些条件不满足，则分片不会被移动。

下面这些设置是 _dynamic_，可以让正在运行的索引从一组节点移到另一组去：

`index.routing.allocation.include.{attribute}`::

    将索引分配给属性值 `{attribute}` 包含一个配置的以半角逗号分隔的值中的一个节点上。

`index.routing.allocation.require.{attribute}`::

    将索引分配给属性值 `{attribute}` 包含全部配置的以半角逗号分隔的值中的一个节点上。

`index.routing.allocation.exclude.{attribute}`::

    将索引分配给属性值 `{attribute}` 不包含配置的以半角逗号分隔的值中的一个节点上。

下面的这些特别属性也是支持的：

[horizontal]
`_name`::   通过节点名称匹配节点
`_ip`::     通过IP地址匹配节点（与主机名关联的IP地址）
`_host`::   通过主机名匹配节点

所有属性值可以通过通配符设置，如：

[source,js]
------------------------
PUT test/_settings
{
  "index.routing.allocation.include._ip": "192.168.2.*"
}
------------------------
// AUTOSENSE
