[[setup-repositories]]
== 仓库

对于基于 APT 和 YUM 的发行版本我们也有可用的仓库. 注意我们仅提供二进制包, 但是没有源码包, 因为源码包是作为 Elasticsearch 的一部分来构建的.

我们将主版本分隔成单独的URL, 以免在主版本间升级发生意外.对于所有 2.x 发布版使用 2.x 作为版本号, 对于 3.x.y 使用 3.x 作为版本号等等...

我们使用的是 PGP 密钥 https://pgp.mit.edu/pks/lookup?op=vindex&search=0xD27D666CD88E42B4[D88E42B4],
Elasticsearch 带指纹的签名密钥

    4609 5ACC 8548 582C 1A26 99A9 D27D 666C D88E 42B4

来签名我们所有的包. 可以参考 https://pgp.mit.edu.

[float]
=== APT

下载并安装公共签名密钥:

[source,sh]
--------------------------------------------------
wget -qO - https://packages.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
--------------------------------------------------

保存仓库定义到 +/etc/apt/sources.list.d/elasticsearch-{major-version}.list+ 文件中:

["source","sh",subs="attributes,callouts"]
--------------------------------------------------
echo "deb http://packages.elastic.co/elasticsearch/{major-version}/debian stable main" | sudo tee -a /etc/apt/sources.list.d/elasticsearch-{major-version}.list
--------------------------------------------------

[WARNING]
==================================================
使用上面描述的 `echo` 方法来新增 Elasticsearch 仓库. 不要使用 `add-apt-repository`, 因为
它还会增加 `deb-src` 项, 但是我们不提供源码包.如果你已经增加了 `deb-src` 项, 你会看到像下面这样的错误:

    Unable to find expected entry 'main/source/Sources' in Release file (Wrong sources.list entry or malformed file)

从 `/etc/apt/sources.list` 文件中删除 `deb-src` 项, 安装就可以如预期的那样工作.
==================================================

运行 apt-get update 并且仓库可以使用了. 你可以使用如下命令安装 Elasticsearch:

[source,sh]
--------------------------------------------------
sudo apt-get update && sudo apt-get install elasticsearch
--------------------------------------------------

[WARNING]
==================================================
如果同一个 Elasticsearch 目录存在两个相同项, 在执行 `apt-get update` 的时候你会看到如下错误:

["literal",subs="attributes,callouts"]
Duplicate sources.list entry http://packages.elastic.co/elasticsearch/{major-version}/debian/ ...`

检查 +/etc/apt/sources.list.d/elasticsearch-{major-version}.list+ 文件中的重复项或者在
 `/etc/apt/sources.list.d/` 和 `/etc/apt/sources.list` 文件中定位重复项.
==================================================

可以配置 Elasticsearch 在系统启动时自动启动. 如果你系统的发行版本使用的是 SysV init启动方式,
那么你需要运行如下命令:

[source,sh]
--------------------------------------------------
sudo update-rc.d elasticsearch defaults 95 10
--------------------------------------------------

如果你系统的发行版本使用的是 systemd 启动方式, 你就需要运行如下两个命令:

[source,sh]
--------------------------------------------------
sudo /bin/systemctl daemon-reload
sudo /bin/systemctl enable elasticsearch.service
--------------------------------------------------

[float]
=== YUM

下载并安装公共签名密钥:

[source,sh]
--------------------------------------------------
rpm --import https://packages.elastic.co/GPG-KEY-elasticsearch
--------------------------------------------------

在 `/etc/yum.repos.d/` 目录下一个后缀名为 `.repo` 的文件 (例如 `elasticsearch.repo`) 中增加以下内容

["source","sh",subs="attributes,callouts"]
--------------------------------------------------
[elasticsearch-{major-version}]
name=Elasticsearch repository for {major-version} packages
baseurl=http://packages.elastic.co/elasticsearch/{major-version}/centos
gpgcheck=1
gpgkey=http://packages.elastic.co/GPG-KEY-elasticsearch
enabled=1
--------------------------------------------------

现在你的仓库可以使用了. 你可以使用如下命令安装 Elasticsearch:

[source,sh]
--------------------------------------------------
yum install elasticsearch
--------------------------------------------------

可以配置 Elasticsearch 在系统启动时自动启动. 如果你系统的发行版本使用的是 SysV init启动方式,
那么你需要运行如下命令:

WARNING: 对于仍然使用 RPM v3, 像 CentOS5 这样基于 rpm 的发行版本, 仓库将无法工作.

[source,sh]
--------------------------------------------------
chkconfig --add elasticsearch
--------------------------------------------------

如果你系统的发行版本使用的是 systemd 启动方式, 你就需要运行如下两个命令:

[source,sh]
--------------------------------------------------
sudo /bin/systemctl daemon-reload
sudo /bin/systemctl enable elasticsearch.service
--------------------------------------------------
